# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.CharField(default='url', max_length=100),
            preserve_default=False,
        ),
    ]
