# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import restapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20180314_0520'),
    ]


    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
            ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('category_name', models.CharField(max_length=100)),
        ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='screenshot',
            field=models.ImageField(upload_to=restapi.models.random_filename),
        ),
    ]
