# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20180315_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='GD', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='screenshot',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
